version: "3.8"

services:
  mysql:
    image: mysql:8.0.40
    command: --default-authentication-plugin=mysql_native_password --ssl=0 --default-time-zone='+00:00'
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: Here!Lives@A#Happy4Little%Password^
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    networks:
      - scream1
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uuser -puserpassword"]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 30s

  # Restore Service
  scream-restore:
    build:
      context: .
      dockerfile: SCREAM.Service.Restore/Dockerfile
    environment:
      - API_URL=http://host.docker.internal:5102
      - MYSQL_BACKUP_ENCRYPTION_KEY=your-encryption-key-here
      - MYSQL_BACKUP_HOSTNAME=mysql
      - MYSQL_BACKUP_USERNAME=user
      - MYSQL_BACKUP_PASSWORD=userpassword
      - MYSQL_BACKUP_THREADS=4 
    ports:
      - "8002:8002"
    networks:
      - scream1
    restart: on-failure
    volumes:
      - ./backups:/backups
    depends_on:
      - mysql

  # Backup Service
  scream-backup:
    build:
      context: .
      dockerfile: SCREAM.Service.Backup/Dockerfile
    environment:
      - API_URL=http://host.docker.internal:5102
      - MYSQL_BACKUP_ENCRYPTION_KEY=your-encryption-key-here
      - MYSQL_BACKUP_HOSTNAME=mysql
      - MYSQL_BACKUP_USERNAME=user
      - MYSQL_BACKUP_PASSWORD=userpassword
      - MYSQL_BACKUP_DATABASE=SCREAM
      - MYSQL_BACKUP_THREADS=4
    ports:
      - "8001:8001"
    networks:
      - scream1
    restart: on-failure
    volumes:
      - ./backups:/backups
    depends_on:
      - mysql

networks:
  scream1:
    external: true