// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCREAM.Data;

#nullable disable

namespace SCREAM.Data.Migrations
{
    [DbContext(typeof(ScreamDbContext))]
    [Migration("20250304194423_StorageTargets")]
    partial class StorageTargets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("SCREAM.Data.Entities.BackupItems.BackupItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSelected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BackupItem");

                    b.HasDiscriminator<string>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SCREAM.Data.Entities.DatabaseConnection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DatabaseConnections", (string)null);
                });

            modelBuilder.Entity("SCREAM.Data.Entities.StorageTargets.StorageTarget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StorageTargets", (string)null);

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SCREAM.Data.Entities.BackupItems.EventItem", b =>
                {
                    b.HasBaseType("SCREAM.Data.Entities.BackupItems.BackupItem");

                    b.HasDiscriminator().HasValue("Event");
                });

            modelBuilder.Entity("SCREAM.Data.Entities.BackupItems.FunctionProcedureItem", b =>
                {
                    b.HasBaseType("SCREAM.Data.Entities.BackupItems.BackupItem");

                    b.HasDiscriminator().HasValue("FunctionProcedure");
                });

            modelBuilder.Entity("SCREAM.Data.Entities.BackupItems.TableDataItem", b =>
                {
                    b.HasBaseType("SCREAM.Data.Entities.BackupItems.BackupItem");

                    b.Property<long>("RowCount")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("TableData");
                });

            modelBuilder.Entity("SCREAM.Data.Entities.BackupItems.TableStructureItem", b =>
                {
                    b.HasBaseType("SCREAM.Data.Entities.BackupItems.BackupItem");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("TableStructure");
                });

            modelBuilder.Entity("SCREAM.Data.Entities.BackupItems.TriggerItem", b =>
                {
                    b.HasBaseType("SCREAM.Data.Entities.BackupItems.BackupItem");

                    b.HasDiscriminator().HasValue("Trigger");
                });

            modelBuilder.Entity("SCREAM.Data.Entities.BackupItems.ViewItem", b =>
                {
                    b.HasBaseType("SCREAM.Data.Entities.BackupItems.BackupItem");

                    b.HasDiscriminator().HasValue("View");
                });

            modelBuilder.Entity("SCREAM.Data.Entities.StorageTargets.AzureBlobStorageTarget", b =>
                {
                    b.HasBaseType("SCREAM.Data.Entities.StorageTargets.StorageTarget");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("SCREAM.Data.Entities.StorageTargets.GoogleCloudStorageTarget", b =>
                {
                    b.HasBaseType("SCREAM.Data.Entities.StorageTargets.StorageTarget");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceAccountKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("StorageTargets", t =>
                        {
                            t.Property("BucketName")
                                .HasColumnName("GoogleCloudStorageTarget_BucketName");
                        });

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("SCREAM.Data.Entities.StorageTargets.LocalStorageTarget", b =>
                {
                    b.HasBaseType("SCREAM.Data.Entities.StorageTargets.StorageTarget");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("SCREAM.Data.Entities.StorageTargets.S3StorageTarget", b =>
                {
                    b.HasBaseType("SCREAM.Data.Entities.StorageTargets.StorageTarget");

                    b.Property<string>("AccessKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(1);
                });
#pragma warning restore 612, 618
        }
    }
}
