// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCREAM.Data;

#nullable disable

namespace SCREAM.Data.Migrations
{
    [DbContext(typeof(ScreamDbContext))]
    partial class ScreamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");
#pragma warning restore 612, 618
        }
    }
}
